! Prueba de error de Proc-Funcs
let
  rec
   func x() : x ~ 1 |
   proc y() ~ put('z') |
   func z() : z ~ 2
  end
in
  x()
end